
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int MayorQue = 15;
  public static final int Mas = 11;
  public static final int coma = 3;
  public static final int numero = 2;
  public static final int flecha = 8;
  public static final int InterrogacionC = 9;
  public static final int AdmiracionC = 14;
  public static final int PorCiento = 19;
  public static final int LlaveC = 18;
  public static final int Or = 12;
  public static final int LlaveA = 17;
  public static final int guion = 7;
  public static final int Asterisco = 10;
  public static final int Cadena = 21;
  public static final int EOF = 0;
  public static final int id = 20;
  public static final int ASSCI = 24;
  public static final int comentarioMulti = 22;
  public static final int CONJ = 13;
  public static final int error = 1;
  public static final int comentario = 23;
  public static final int Punto = 4;
  public static final int MenorQue = 16;
  public static final int PuntoComa = 6;
  public static final int DosPuntos = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "numero",
  "coma",
  "Punto",
  "DosPuntos",
  "PuntoComa",
  "guion",
  "flecha",
  "InterrogacionC",
  "Asterisco",
  "Mas",
  "Or",
  "CONJ",
  "AdmiracionC",
  "MayorQue",
  "MenorQue",
  "LlaveA",
  "LlaveC",
  "PorCiento",
  "id",
  "Cadena",
  "comentarioMulti",
  "comentario",
  "ASSCI"
  };
}

